// 怪物定义表：杂兵/精英/Boss 数值与 AI 配置
import { EnemyDef, EnemyKind } from 'game/core/Types';

export const enemyDefs: Record<EnemyKind, EnemyDef> = {
	walker: {
		kind: 'walker',
		name: '魔影行者',
		radius: 14,
		maxHp: 30,
		moveSpeed: 70,
		damage: 8,
		exp: 2,
		color: 0x3fbf5f,
		isElite: false,
		isBoss: false,
		ai: 'chase',
	},
	runner: {
		kind: 'runner',
		name: '疾风斥候',
		radius: 11,
		maxHp: 20,
		moveSpeed: 140,
		damage: 6,
		exp: 2,
		color: 0xb8e34f,
		isElite: false,
		isBoss: false,
		ai: 'chase',
	},
	tank: {
		kind: 'tank',
		name: '重甲卫士',
		radius: 22,
		maxHp: 90,
		moveSpeed: 40,
		damage: 15,
		exp: 5,
		color: 0x1f8f4f,
		isElite: false,
		isBoss: false,
		ai: 'chase',
	},
	ranger: {
		kind: 'ranger',
		name: '蚀骨射手',
		radius: 13,
		maxHp: 28,
		moveSpeed: 80,
		damage: 10,
		exp: 4,
		color: 0x3fcfbf,
		isElite: false,
		isBoss: false,
		ai: 'chaseShoot',
		shootInterval: 2.2,
		shootSpeed: 220,
	},
	charger: {
		kind: 'charger',
		name: '狂怒冲锋者',
		radius: 15,
		maxHp: 45,
		moveSpeed: 90,
		damage: 14,
		exp: 4,
		color: 0xff9f3f,
		isElite: false,
		isBoss: false,
		ai: 'charge',
		chargeCooldown: 2.6,
		chargeSpeed: 340,
	},
	shield: {
		kind: 'shield',
		name: '壁垒守卫',
		radius: 16,
		maxHp: 60,
		moveSpeed: 55,
		damage: 10,
		exp: 5,
		color: 0x7f9fcf,
		isElite: false,
		isBoss: false,
		ai: 'shield',
		shieldRadius: 0.9,
	},
	exploder: {
		kind: 'exploder',
		name: '爆裂魔种',
		radius: 13,
		maxHp: 25,
		moveSpeed: 110,
		damage: 25,
		exp: 4,
		color: 0xff5f3f,
		isElite: false,
		isBoss: false,
		ai: 'suicide',
	},
	elite: {
		kind: 'elite',
		name: '精英·血瞳统领',
		radius: 20,
		maxHp: 300,
		moveSpeed: 75,
		damage: 18,
		exp: 30,
		color: 0xbf5fff,
		isElite: true,
		isBoss: false,
		ai: 'chase',
		shootInterval: 3.2,
		shootSpeed: 260,
	},
	boss: {
		kind: 'boss',
		name: '深渊领主',
		radius: 34,
		maxHp: 1500,
		moveSpeed: 55,
		damage: 25,
		exp: 200,
		color: 0xcf2f3f,
		isElite: false,
		isBoss: true,
		ai: 'boss',
		shootInterval: 2.5,
		shootSpeed: 200,
	},
};

// 获取怪物定义（带防御式回退，避免未知 kind 崩溃）
export function getEnemyDef(kind: EnemyKind): EnemyDef {
	const def = enemyDefs[kind];
	if (def === undefined) return enemyDefs.walker;
	return def;
}

// 波次精英候选（精英波从中抽取基底种类）
export const eliteKinds: EnemyKind[] = ['walker', 'runner', 'tank', 'ranger', 'charger', 'shield', 'exploder'];
